### ISSUE TITLE
Python and Node addon library have different behavior when setProperty failed.

### ISSUE THREAD

**Issue by sogaani** [WebThingsIO/gateway-addon-python#17]
* Node: return current value.
* Python: no response until calling onPropertyChanged.

I'd prefer to return fails message like action. Because, I want to use setProperty for checking that the device is online. 

I figured out this issue on google actions App review.
They have a test case which checks that the google actions App return the device state.

The test case is run like so:
1. Pair device(s) to Google Home
2. Ask, “OK Google, is the <device name> on?”
    *  Expected response if device is on: “The <device name> is on.”
    *  Expected response if device is off: “The <device name> is off.”
3. Remove the device from power (meaning that we simply unplug the test device from all power sources, without removing the device’s pairing information)
4. After a delay, ask “OK Google, is the <device name> on?”
    Expected response within 30 minutes – 1 hour: “It looks like the <device name> isn’t available right now.”

Thing does not have any state like online or unplugged. So, I'm using this issue check the device is online.

**Comment by mrstegeman** [comment]
`gateway-addon-python` assumes that setting a property value won't fail. Maybe that's invalid, though. The relevant bits of code are:

* Node: https://github.com/mozilla-iot/gateway/blob/master/src/plugin/addon-manager-proxy.js#L210
* Python: https://github.com/mozilla-iot/gateway-addon-python/blob/master/gateway_addon/addon_manager_proxy.py#L234

**Comment by sogaani** [comment]
Related wot script spec https://w3c.github.io/wot-scripting-api/#the-writeproperty-method 
If we follow wot spec, maybe python addon should raise exception on failing setProperty?

**Comment by mrstegeman** [comment]
We don't really follow that spec at all, so I wouldn't go by that. However, I'm not opposed to wrapping the `set_value()` call in a try/except. It would match the node library, then.

What are you suggesting we do on reject/exception, though? The node library sends back a property change notification.

**Comment by sogaani** [comment]
My suggestion is that If we catch reject/exception, addon-proxy send a error message "setProperty is failed" to the Gateway, and the Gateway return a error response for 'PUT /things/:thingId/:properties/:propertyName'.

**Comment by mrstegeman** [comment]
#18 will give us the same behavior as the node library. We can build on that to send back an error message.

I kind of like having the property change notification, that way the UI gets updated back to the current value.

**Comment by sogaani** [comment]
#18 looks good!

> I kind of like having the property change notification, that way the UI gets updated back to the current value.

Does this comment mean that send propertyChange message on websocket and response errors on REST API when `setProperty` via REST API is failed?

**Comment by mrstegeman** [comment]
I think it would be appropriate to send back the current value as part of an error message in both cases, rather than having a property notification AND an error message. Unfortunately, our WoT spec doesn't yet define what to do when errors occur.
