### ISSUE TITLE
Github release numbers vs others

### ISSUE THREAD

**Issue by jernst** [WebThingsIO/gateway-addon-python#34]
The most current release of this project on Github ( https://github.com/mozilla-iot/gateway-addon-python/releases ) is 0.4.0, dated January 17. This is also the most recent git tag.

The commit log, on the other hand, implies ( https://github.com/mozilla-iot/gateway-addon-python/commit/6e5331967332d0b5ee40890c3d3d0c4b51dddd0d ) it is now 0.8.0.

Suggestion: have a single defined way for how to get the most current release, e.g. github release package, or git tag, but not both, so they are easier to keep in sync.

**Comment by mrstegeman** [comment]
I have not done a great job of properly versioning this package. With the upcoming 0.8 release of the gateway, I intend to keep both gateway-addon packages versioned the same as the gateway and pin the versions properly. Until this point, our builds have just fetched the latest version.

**Comment by mrstegeman** [comment]
See: mozilla-iot/gateway#1644
