### ISSUE TITLE
Should there be a package.json?

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway-addon-python#40]
The TPLink module has a package.json file in its root directory. At the same time its setup.py is mostly empty.

Should this example also have the JSON file? Or do both methodes of 'presenting' the add-on work? If so, which is preferred?

**Comment by mrstegeman** [comment]
This is not an add-on at all. It's a Python module used by the various add-ons, so it doesn't make sense to have a `package.json`.

All add-ons, regardless of language, have a `package.json`, which is where the gateway gathers add-on metadata.
