### ISSUE TITLE
How to pre-populate adapter.devices from existing things in Gateway?

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway-addon-python#41]
I am building an adapter for MySensors.

Building up the adapter devices list by adding device objects works fine.

However, I wonder if it's possible to take all the things that have already been accepted into the Gateway, and go in the other direction: populate the devices object from the devices already there.

To give a practical example: I have a smart door lock device with a password.

On the first go-around, the user adds the things. He/she can then set the password value as a thing property.

Now, when the WebThings gateway or the device reboots, I'd like the device to ask the already existing password (and current door lock status) from the gateway somehow. I'd like the gateway to be the 'single source of truth', as it were. But this would require that the adapter gets all the existing devices and properties back somehow when its initiated.

I looked through this code to see if such a feature exists. Am I right in understanding it doesn't?

If not, do you have any recommendation for this situation?

**Comment by mrstegeman** [comment]
A couple points to make here.

1. Other adapters handle the password storage by keeping them in the database. For an example, you can look the [HomeKit add-on](https://github.com/mozilla-iot/homekit-adapter#license). For that adapter, each device has a separate PIN code. After the user enters it, the adapter handles storing that in the database. When it starts up again, it will read back the password and such as necessary.
2. The gateway doesn't store cached property values across reboots, nor am I sure that would actually be useful. After the gateway has been down for some arbitrary amount of time, all property values could have changed, so it makes no sense to start with some old value, rather than just resetting. The adapter should handle polling the values when it starts up.

**Comment by flatsiedatsie** [comment]
Thanks for the explanation. I'll look into the Homekit adapter.

I can design my way around this, to be sure. I could store the updated phone number on the lock's EEPROM, and then repopulate the Gateway interface with it if the lock is rebooted. Similarly, I could store the last state of the lock on the device, and on reboot go back to that last state.

In other words, I could make the devices themselves the source of truth. But at the moment all my devices treat the controller as the 'source of truth' since that's how a lot of them could function in the past. Right now my devices would do this two-step:
1. Ask the controller if there is a last known preferred value.
2. If not, or if there is no reply, then the device goes into its default state. In the case of the smart lock this means the door is now unlocked, for safety/fire reasons.

I will change the devices, no problem. But I'd still like to make the case that the Gateway could be a good good source of truth.

First, while it's true the gateway could be off for a long period of time, that feels like a non-normal situation. In my experience, it's more likely that the devices (which are in the living area) are power cycled while the controller (hidden in a meter cabinet somewhere, in my case on a UPS) keeps running. This is why the controller as a source of truth, in general, feels right? It's the boss!

Another practical reason is that it could improve recovery speed. Right now my adapter has to receive three message types from the devices before it can generate a property:
1. A 'presentation' message that says "hey, a variable is coming, and this is its name". This is sent at boot.
2. A message that has the actual variable content, such as the content of an incoming SMS, or the latest value of a sensor. It further defines the type of the variable, such as 'text' or 'boolean'.
3. An optional message that contains the unit (e.g. 'ppm')

I cannot really create the property on the Gateway until I have received all messages. But in practice that may take a little while: some sensors take 5 minutes to send the first actual value.

After receiving the first presentation message, I can create the device on the gateway. But until the actual data comes in, it would not have any properties. And I have no way of knowing if all properties have arrived, so I can't just wait for that and do it all in one go).

In practice this would mean that the user could see a fully populated device one moment, and then on reboot it may go back to being presented as a device without properties for a short while.

One way this issue could be avoided is if the adapter could ask the gateway "hey, which devices that this adapter created earlier did the user end up turning into things? Could you give their names and what properties they have?".

As I write this I see the security risk :-)

**Comment by mrstegeman** [comment]
I definitely see your motivation. We have several other protocols that suffer from similar slowness issues (HomeKit, Z-Wave, Zigbee). But yes, there are issues with the "gateway as source of truth" approach as well.

Let me use HomeKit as an example again. HomeKit can operate over wi-fi (super fast) or Bluetooth (super slow). For some of the Bluetooth devices, the whole pairing process plus reading properties and such can take a _very_ long time. What I've done for those is essentially keep the device objects local to the adapter until fully populated before sending them to the gateway via `handleDeviceAdded` (see [this code](https://github.com/mozilla-iot/homekit-adapter/blob/master/lib/homekit-adapter.js#L186-L189)). Each device has a Promise which will only resolve once fully populated. That helps get around the weird in-between states, at least.

**Comment by dhylands** [comment]
The zigbee and zwave adapters both cache information and values from devices in local files on disk.

This is done primarily to support battery powered devices which only report in when their state changes. If the gateway reboots then this cached information is used until the next device report occurs.

**Comment by flatsiedatsie** [comment]
@dhylands Thanks. If I understand correctly you're saying I could just have the adapter remember the last known state itself. That's definitely an option, and in practice would probably be a lot like the Gateway storing it.


This week was another instance in which I realized that it would be useful to find out which device the user actually accepted as a thing. I would exploring building an add-on that does presence detection on the local network. For example: if a phone is on the network, this could be treated as a signal that the user is home.

The add-on could do a scan of the network and just dump all the found devices into the devices list. The user could then select which one they turn into a thing.

This solution could already make the list of possible new things very messy and long, which would be annoying for users to scroll through.

For this to work, automations would need to be able to respond to devices being 'connected' to the adapter or not. Conceptually this feels good, and a device which has partial opacity when not on the network could look good too. A downside is that I can't influence how long it takes for the Gateway to say "ok, I haven't seen this device in a while now, I am going to set is as disconnected now". I could be wrong here.

If this is used, a new scan of the network could just re-affirm that those devices exist.

If automations can't respond to a device being connected or not, there is the more obvious option to just create a toggle property for the device. If the device is on the network, the toggle is set to 1, else 0.

The issue here is that the adapter would have to keep a list of all devices it has ever found. It would have to know that "iphone 1" exists, even when it isn't on the network right now. And since there is no way to ask the Gateway which mobile devices the user actually cares about / which ones have been turned into things, the only recourse is to just keep a log of all devices ever seen, and toggle them whenever they are seen or have not been seen for an X amount of time.

The list of devices the user sees when they click on (+) could become overwhelming.

A third option is to wait until there is a way to create some kind of custom selection interface for the adapter, so that it can in fact know which device's presence the user cares about, without having to 'abuse' the Mozilla onboarding system.

**Comment by flatsiedatsie** [comment]
To test all this I created an add-on that does presence detection on the local network.

Some things I noticed during development:
- I resorted to adding "presence - " in the name of each device. This was to help differentiate devices in the 'device inbox' (add thing page). Perhaps this discombobulation could be something that is part of the gateway in the future, in order to avoid all add-ons creating their own prefix structure in the names.
- Not knowing which device the user has turned into a thing means the add-on remembers every device it ever spotted, and that is always presents all these devices on the 'add new thing' page. This should not be all that problematic as long as the user does not use the gateway in a setting where a lot of devices connect to the network. I added a timestamp to when a device was spotted, and added a feature to 'prune' old devices. The user can select after how many weeks or not being spotted a device should be 'forgotten'.

Being able to create a more complex UI for an add-on would perhaps allow users to not have to deal with the universal 'add new thing' inbox, but instead handle that process internally.

If add-ons could bring along their own UI, it would also allow for more interesting things like being able to set the period that a device should be unseen before it is marked as 'away'. Currently the add-on has one 'time window' for all devices. The user can change this, but it's still one size fits all.

Another solution to this though would be to just update a number property on the thing which represents how many minutes ago it was last seen. Automations could then perhaps simply say "if iPhone's 'last seen x minutes ago' counter is bigger than 60, then disable the heater". I don't know if the rule system currently supports this, time to find out.

**Comment by flatsiedatsie** [comment]
I think we can close this. If any of the suggestions or thought are relevant I can turn them into separate issues.

For anyone finding this, the conclusion is:
- Communication is not bi-directional, and for now it looks like this will be the status quo.
- Devices that were spotted but that the user doesn't want to turn into a thing can be removed in two ways. The first is by waiting. A pruning function simply removes devices if they haven't been spotted in a long time (weeks). The other is that if you want to remove a thing from the 'thing inbox' right now, then you can accept it and then delete it. This is a bit of a work-around, but at least it offers users some way to de-clutter their 'thing inbox' immediately.
