### ISSUE TITLE
What are the options when creating a settings interface?

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway-addon-python#43]
I've had look at a number of adapters, but I haven't found what I'm looking for.

I have found a dropdown option, and a string input.

I am hoping that there is an option to create a checkbox. Is this available?

**Comment by mrstegeman** [comment]
https://github.com/mozilla-iot/thing-url-adapter/blob/master/package.json#L40-L61

We conform to a subset of the JSON Schema Validation spec.

**Comment by flatsiedatsie** [comment]
Ah, nevermind, I hit the jackpot:
https://github.com/mozilla-iot/virtual-things-adapter/blob/master/package.json

**Comment by flatsiedatsie** [comment]
If I want to add a new add-on to the add-on list, but it doesn't actually have any settings, should I still include the 'schema' part of the package.json file?

**Comment by mrstegeman** [comment]
No, only include the `config` and `schema` objects if you actually need them.

**Comment by flatsiedatsie** [comment]
I'd like to make a button in settings. Something like "forget all devices". I don't see a button option though.

Maybe it can be 'hacked'? I know it would be possible to create a checkbox, and check if the user has set it. But would is then be possible for the add-on to un-tick that checkbox once is has finished forgetting?

**Comment by mrstegeman** [comment]
No, there's no way to draw a button right now. However, you _can_ do what you're suggesting. To update the config, you can use `save_config`: https://github.com/mozilla-iot/gateway-addon-python/blob/master/gateway_addon/database.py#L84-L111

**Comment by flatsiedatsie** [comment]
Thanks!

To test my conjecture about the issues of one-way communication with the gateway I decided to do a practical test. I've created an add-on that does network presence detection:
https://github.com/flatsiedatsie/webthings-network-presence-detection

As I suspected, not having a feedback channel from the Gateway about which devices are actually things is tricky.

Thinking out loud again: would it be possible to check if an update to a value on the gateway was successful? If the `notify_property_changed` or `handle_device_added` function returns true or false, that would be one way of sussing out if the user has actually turned the presented device into a thing?

The add-on currently resorts to storing al the devices it has ever seen in a json file. Is that.. allowed? Or should add-ons store all their data in the database? I suspect storing things in the database is the best/only way of keeping that json file between updates?

**Comment by mrstegeman** [comment]
You can definitely write your own JSON file or database or whatever. Examples:
* Custom database:
  * https://github.com/freaktechnik/flic-button-adapter/blob/master/adapter.js#L108-L114
  * https://github.com/freaktechnik/flic-button-adapter/blob/master/adapter.js#L181
* JSON files:
  * https://github.com/mozilla-iot/zigbee-adapter/blob/master/zb-adapter.js#L60-L68
  * https://github.com/mozilla-iot/zigbee-adapter/blob/master/zb-adapter.js#L102-L103
* Using the gateway's database:
  * https://github.com/mozilla-iot/homekit-adapter/blob/master/lib/homekit-database.js

I don't think your two ideas are going to give you any real feedback. The only thing I can think of right now is to give each device a password of some sort. The user would have to enter the password before saving the device, so you'd get some feedback then. Alternatively, you could use `send_pairing_prompt()` to tell the user to take some sort of action on the thing after saving it.

**Comment by flatsiedatsie** [comment]
I'm currently scanning the ALSA list of available hardware, and would like to use that output to change the available options in a dropdown in the settings page, so that only the hardware that is actually there is selectable. As far as I understand, that's not possible.

I could then try option B, which is to pre-select the most likely device for the user. That way it might already 'just work' out of the box, correct?

> No, there's no way to draw a button right now. However, you _can_ do what you're suggesting. To update the config, you can use `save_config`: https://github.com/mozilla-iot/gateway-addon-python/blob/master/gateway_addon/database.py#L84-L111

So this would basically be like 'auto configuration'?

Can I store other data in the config dictionary, even if those values are not mentioned in the package.json? Is it frowned upon?

Final question: in the `package.json` there is the part of 'required'. How does that work? Of I have a boolean checkbox and I put it in the 'required' part, this does not stop to user from deselecting the checkbox. And it would be odd if they couldn't, because why have the checkbox if you can't un-select it. So what is the 'required' section's purpose?

**Comment by mrstegeman** [comment]
> I could then try option B, which is to pre-select the most likely device for the user. That way it might already 'just work' out of the box, correct?

Correct. You could also allow the user to enter a custom value, if they know what they're doing.

> Can I store other data in the config dictionary, even if those values are not mentioned in the package.json? Is it frowned upon?

Theoretically, yes, but definitely not ideal. If you need to, you can create a secondary file in the config directory, like you do with other add-ons.

> Final question: in the `package.json` there is the part of 'required'. How does that work? Of I have a boolean checkbox and I put it in the 'required' part, this does not stop to user from deselecting the checkbox. And it would be odd if they couldn't, because why have the checkbox if you can't un-select it. So what is the 'required' section's purpose?

`required` indicates that it's required in order to submit the form. In the case of a checkbox, the value is always either true or false, checked or not checked. For the actual spec, see here: https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.5.3

**Comment by flatsiedatsie** [comment]
Thanks for the explanation. I'll stick with making the config files.

> `required` indicates that it's required in order to submit the form. In the case of a checkbox, the value is always either true or false, checked or not checked. For the actual spec, see here: https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.5.3

I didn't quite understand that page.. but in practice I guess this only effects input fields where users can enter a string or a number? These are not allowed to be empty?

**Comment by mrstegeman** [comment]
> but in practice I guess this only effects input fields where users can enter a string or a number? These are not allowed to be empty?

Yes, that would be accurate.

**Comment by mrstegeman** [comment]
I'm going to close this, since there don't seem to be any real action items.

**Comment by flatsiedatsie** [comment]
An action item could be to create some documentation :-) Now I keep coming back to this thread to figure out how to do things. I could help write some if you'd like.

**Comment by mrstegeman** [comment]
We have some things written up already, but they're probably not the best. Please help us make our documentation better if you can!

* https://github.com/mozilla-iot/wiki/wiki/Adapter-API
* https://github.com/mozilla-iot/wiki/wiki/Adapter-IPC
* https://github.com/mozilla-iot/wiki/wiki/Add-On-Configuration
* https://github.com/mozilla-iot/wiki/wiki/Add-On-System-Design
