### ISSUE TITLE
Run python code as root?

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway-addon-python#45]
I found a python library that emulates `arping`, but it still requires root to create the packets.

https://github.com/stellarbit/aioping

I know it's not possible for an add-on to require actual programs. But is it possible to run certain python code as root?

**Comment by mrstegeman** [comment]
Not really. A script can re-launch itself with `sudo`, or fork off a little process (as sudo) to do some work.

**Comment by flatsiedatsie** [comment]
That 'fork a little proces' sounds like it might be an idea?

**Comment by mrstegeman** [comment]
We try not to allow add-ons to do work as root, unless it's an exceptional circumstance where there's no other way to do what is needed.
