### ISSUE TITLE
Is it possible to add a hyperlink to a thing?

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway-addon-python#46]
The WoT schema seems to mention that things could have URL's. 

```
      "rel": "alternate",
      "href": "wss://mywebthingserver.com/things/lamp"
```

I believe I've seen the hyperlink chain icon somewhere as well.

Is it possible to (theoretically) give a thing a hyperlink that the user can click on? And if so, is that possible with the current add-on system?

**Comment by mrstegeman** [comment]
Apparently not! The code to do so was never copied over from the Javascript bindings.

**Comment by flatsiedatsie** [comment]
Any hint on how that array should be filled? And will filling it with a link, and then updating the thing, lead to a link icon on the thing somewhere that opens that link?

**Comment by mrstegeman** [comment]
You can pull in the changes from #47 yourself, i.e. override `as_dict()` and `as_thing()`, if you want to try this out.

Example: https://github.com/freaktechnik/netatmo-weather-adapter/blob/master/adapter.js#L114-L120

**Comment by flatsiedatsie** [comment]
@mrstegeman Thanks. I tried to find where on the Pi the `device.py` file is located so I could manually add the changes, but I couldn't find it.

**Comment by mrstegeman** [comment]
I meant within your own `Device` subclass. Just copy in the `as_dict` and `as_thing` methods from `device.py` into your subclass.

**Comment by flatsiedatsie** [comment]
It works! Thanks!

**Comment by flatsiedatsie** [comment]
Am I correct in understanding that when the next version of the Gateway is released the versions of `as_dict` and `as_thing` that I copied into my code can be removed?

**Comment by mrstegeman** [comment]
Yes, that’s correct. However, if users are still on the previous version, they won’t have the links available.
