### ISSUE TITLE
Add-on downloads multiple files to its own directory, is that ok?

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway-addon-python#49]
I'm working on an add-on that will allow users to easily upload code to an Arduino that they attach to the WebThings gateway via USB.

The add-on will present the user with a list of sketches that can be installed onto it. These sketches will be downloaded/updated when the add-on starts.

Currently the add-on saves these files into a 'source' directory inside the add-on directory.
- Is this location 'ok'? Or should another location be used? (you linked to an example that seems to suggest each user can have their own [home directory](https://github.com/mozilla-iot/zigbee-adapter/blob/master/zb-adapter.js#L60-L68)?) I know that if the user deletes the add-on that all the files in the 'source' directory will be deleted too, but that is fine.
- Users will be able to provide their own links to Arduino sketches which will then be downloaded and added to the list. Is this ok? Do you consider it a security risk? The add-on checks that the URL's provided by users start with 'http' and end with '.ino', and they are turned into UTF8 files.

**Comment by mrstegeman** [comment]
You should not save files into the add-on source directory, if you need them to be persistent. This directory is completely removed when the add-on is updated.

Instead, you should save things into the profile directory, i.e. `~/.mozilla-iot`. That's what you did in your network presence detection add-on. Here is another example: https://github.com/mozilla-iot/onvif-adapter/blob/master/lib/onvif-device.js#L18-L27

**Comment by flatsiedatsie** [comment]
By 'not persistent', do you mean that they will be deleted when the add-on is removed? That would be fine in this case.

Or do you mean they will be removed every time the system Gateway restarts? In that case using the profile directory will indeed be a better option.

**Comment by mrstegeman** [comment]
Those files would be removed when the add-on itself is either removed or updated to a new version.

**Comment by flatsiedatsie** [comment]
That would be totally fine.
