### ISSUE TITLE
Shipping add-on with a binary

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway-addon-python#50]
I'm working on an add-on that relies on the [Arduino CLI](https://github.com/arduino/arduino-cli) to upload code to Arduino's that users plug into the WebThings Gateway via USB.

Currently the add-on simple has the Raspberry Pi version packaged inside it.

- What is the proper procedure for getting an add-on accepted that brings along a binary?
- I believe the WebThings Gateway already know not to present Linux add-ons to users on other platforms such as Windows/Mac, correct? Would it be preferable if versions of the binary for Windows/Mac/Other were also included?

**Comment by mrstegeman** [comment]
Quite a few of our Node add-ons have precompiled binaries included. Essentially, we break them out by architecture. For example: https://github.com/mozilla-iot/addon-list/blob/1e46a9232193e5b1c5bd9c4c446e6f18f090cd16/list.json#L2026-L2123

Another option is to package all of the binaries in the same package and select the proper one at runtime. That's what [this add-on](https://github.com/freaktechnik/flic-button-adapter) does.
