### ISSUE TITLE
Get more general settings from the Gateway?

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway-addon-python#52]
Is it possible for an add-on to read if the Gateway is currently set to imperial or metric?
https://forum.mysensors.org/topic/10491/mysensor-controller-config-imperial-false-setting/7

This is probably related to a lot of other issues about setting the preferred time, etc.

**Comment by mrstegeman** [comment]
Not yet. See: https://github.com/mozilla-iot/gateway/issues/1523
