### ISSUE TITLE
Extension add-ons questions

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway-addon-python#65]
I'm exploring the new add-on system, and have some small questions.

I also know I'm playing with alpha functionality, and I assume most of the errors I come across will be because of my coding/stumbling around the code. A lot of them aren't related to the new functionality either. But I'll share them anyway, in case they are actually relevant. Feel free to ignore any or all of them.

First of though: how cool is this! I have been able to load in some basic html, and it's so cool to be able to extend the UI so beautifully. Awesome!

Ok, onto the list of things I noticed:

- I suspect there will be a lot of add-ons that extend the UI. That side menu is going to get pretty full.

- Is there a faster way to start the gateway than doing `npm start`? It takes a while for it to boot up.

- Is WebAssembly required to use extensions? I'm getting some errors in the console related to it. I have disabled WebAssembly for security reasons.

- Does the WebAssembly code touch a Mozilla server? I noticed this in the code: `https://speaktome-2.services.mozilla.com/`. I hope the gateway doesn't assume it's ok to connect to a web based voice service to do TTS.

- in Firefox (69.0.1, Mac), in the console I see something that's probably related to my security and privacy settings:
-- `Failed to register/update a ServiceWorker for scope ‘http://localhost:8080/’: Storage access is restricted in this context due to user settings or private browsing mode.`
-- `Content Security Policy: The report URI (about:blank) should be an HTTP or HTTPS URI.`
- - `Content Security Policy: The page’s settings observed the loading of a resource at http://localhost:8080/service-worker.js (“worker-src”). A CSP report is being sent.`
- - Followe by two `SecurityError: The operation is insecure.` errors. 

- in Chromium (71, Mac) I see something similar:
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:45 Uncaught (in promise) Error: 500
    at api.js:45
settings/experiments/assistant:1 Failed to load resource: the server responded with a status of 404 (Not Found)
settings/experiments/logs:1 Failed to load resource: the server responded with a status of 404 (Not Found)
chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/lpfulllib.js:1 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
include_language @ chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/lpfulllib.js:1
The FetchEvent for "http://localhost:8080/things" resulted in a network error response: the promise was rejected.
2service-worker.js:45 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at service-worker.js:45
```

- I saw the error below, but it seems to be gone, so most likely it was in my code.
```
ERROR  : Plugin: Candle-manager-addon Unrecognized adapter: Candle-manager-addon Ignoring msg: { messageType: 8197,
  data: 
   { adapterId: 'Candle-manager-addon',
     deviceId: 'candle-device',
     connected: true,
     pluginId: 'Candle-manager-addon' } }
```

- I noticed this when I clicked on 'disable' for the example add-on. This is on a mac with the gateway running on localhost.

```
2019-09-29 15:57:10.875 INFO   : Unloading API handler example-extension
2019-09-29 15:57:10.878 INFO   : example-extension: API Handler example-extension unloaded
2019-09-29 15:57:10.970 ERROR  : 
2019-09-29 15:57:10.971 ERROR  : /Users/username/gateway/build/webpack:/src/plugin/plugin.js:270
        const handler = this.handlers.get(packageName);
^
2019-09-29 15:57:10.971 ERROR  : TypeError: Cannot read property 'get' of undefined
    at Plugin.onMsg (/Users/username/gateway/build/webpack:/src/plugin/plugin.js:270:1)
    at IpcSocket.onData (/Users/username/gateway/node_modules/gateway-addon/lib/ipc.js:144:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Socket._receive (/Users/username/gateway/node_modules/nanomsg/lib/index.js:204:8)
    at Socket.<anonymous> (/Users/username/gateway/node_modules/nanomsg/lib/index.js:218:24)
```

Despite the error, after restarting `npm start`, the add-on was disabled.

- Noticed this in the console too:
```
XHRGEThttp://localhost:8080/settings/experiments/assistant
[HTTP/1.1 404 Not Found 20ms]

XHRGEThttp://localhost:8080/settings/experiments/logs
[HTTP/1.1 404 Not Found 32ms
```

- The default CSS cuts of the top of the content. There's a `transform: translateY(-50%);` that seems to be the culprit.
![candle_manager_extension](https://user-images.githubusercontent.com/805405/65835234-51cee080-e2d3-11e9-9cae-3d812b0de7f4.png)
_Don't worry, the logo won't be that big in the final version :-)_

**Comment by flatsiedatsie** [comment]
Captain's log, continued:

-  For a menu item name, should all words be capitalized? If so, CSS could probably enforce it to a small degree.

**Comment by mrstegeman** [comment]
> First of though: how cool is this! I have been able to load in some basic html, and it's so cool to be able to extend the UI so beautifully. Awesome!

😃 

> * I suspect there will be a lot of add-ons that extend the UI. That side menu is going to get pretty full.

Potentially. Not every extension will need to add a menu entry. For instance, an adapter might have a configuration UI that is linked via an alternate UI link, i.e. https://github.com/mozilla-iot/weather-adapter/blob/master/lib/weather-device.js#L193-L199.

> * Is there a faster way to start the gateway than doing `npm start`? It takes a while for it to boot up.

`npm start` runs `webpack` each time. What we do on the RPi image is run `webpack` at build time and then `npm run run-only` after that.

> * Is WebAssembly required to use extensions? I'm getting some errors in the console related to it. I have disabled WebAssembly for security reasons.

WASM is used by the speech library in the UI, nothing else.

> * Does the WebAssembly code touch a Mozilla server? I noticed this in the code: `https://speaktome-2.services.mozilla.com/`. I hope the gateway doesn't assume it's ok to connect to a web based voice service to do TTS.

Yes, but the assistant/speech functionality can be disable in Settings. It's disabled by default.

> * in Firefox (69.0.1, Mac), in the console I see something that's probably related to my security and privacy settings:
>   -- `Failed to register/update a ServiceWorker for scope ‘http://localhost:8080/’: Storage access is restricted in this context due to user settings or private browsing mode.`
>   -- `Content Security Policy: The report URI (about:blank) should be an HTTP or HTTPS URI.`
> 
> * * `Content Security Policy: The page’s settings observed the loading of a resource at http://localhost:8080/service-worker.js (“worker-src”). A CSP report is being sent.`
> 
> * * Followe by two `SecurityError: The operation is insecure.` errors.

[Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) require a secure context, i.e. running under https. You were using http://localhost.

> * in Chromium (71, Mac) I see something similar:
> 
> 
> ```
> Failed to load resource: the server responded with a status of 500 (Internal Server Error)
> api.js:45 Uncaught (in promise) Error: 500
>     at api.js:45
> settings/experiments/assistant:1 Failed to load resource: the server responded with a status of 404 (Not Found)
> settings/experiments/logs:1 Failed to load resource: the server responded with a status of 404 (Not Found)
> chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/lpfulllib.js:1 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
> include_language @ chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/lpfulllib.js:1
> The FetchEvent for "http://localhost:8080/things" resulted in a network error response: the promise was rejected.
> 2service-worker.js:45 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
>     at service-worker.js:45
> ```

The settings 404 errors are fine. That happens when the experiments are not enabled. The 500 error is a work in progress.

> * I saw the error below, but it seems to be gone, so most likely it was in my code.
> 
> 
> ```
> ERROR  : Plugin: Candle-manager-addon Unrecognized adapter: Candle-manager-addon Ignoring msg: { messageType: 8197,
>   data: 
>    { adapterId: 'Candle-manager-addon',
>      deviceId: 'candle-device',
>      connected: true,
>      pluginId: 'Candle-manager-addon' } }
> ```
> 
> * I noticed this when I clicked on 'disable' for the example add-on. This is on a mac with the gateway running on localhost.
> 
> 
> 2019-09-29 15:57:10.875 INFO : Unloading API handler example-extension
> 2019-09-29 15:57:10.878 INFO : example-extension: API Handler example-extension unloaded
> 2019-09-29 15:57:10.970 ERROR :
> 2019-09-29 15:57:10.971 ERROR : /Users/username/gateway/build/webpack:/src/plugin/plugin.js:270
> const handler = this.handlers.get(packageName);
> ^
> 2019-09-29 15:57:10.971 ERROR : TypeError: Cannot read property 'get' of undefined
> at Plugin.onMsg (/Users/username/gateway/build/webpack:/src/plugin/plugin.js:270:1)
> at IpcSocket.onData (/Users/username/gateway/node_modules/gateway-addon/lib/ipc.js:144:10)
> at emitOne (events.js:116:13)
> at Socket.emit (events.js:211:7)
> at addChunk (_stream_readable.js:263:12)
> at readableAddChunk (_stream_readable.js:250:11)
> at Socket.Readable.push (_stream_readable.js:208:10)
> at Socket._receive (/Users/username/gateway/node_modules/nanomsg/lib/index.js:204:8)
> at Socket. (/Users/username/gateway/node_modules/nanomsg/lib/index.js:218:24)
> 
> ```
> 
> Despite the error, after restarting `npm start`, the add-on was disabled.

The IPC stuff in add-ons is undergoing some major changes right now, so things may not be 100% working.

> - Noticed this in the console too:
> ```
> 
> XHRGEThttp://localhost:8080/settings/experiments/assistant
> [HTTP/1.1 404 Not Found 20ms]
> 
> XHRGEThttp://localhost:8080/settings/experiments/logs
> [HTTP/1.1 404 Not Found 32ms
> 
> ```

Addressed above.

> - The default CSS cuts of the top of the content. There's a `transform: translateY(-50%);` that seems to be the culprit.

Extensions need to handle their own CSS. Things may break across gateway versions with the UI, which is why we have the new `strict_min_version` and `strict_max_version` fields in the manifest.

**Comment by mrstegeman** [comment]
> * For a menu item name, should all words be capitalized? If so, CSS could probably enforce it to a small degree.

Not necessarily. "Log out" is not capitalized.

**Comment by mrstegeman** [comment]
(Closing since there are no issues related to this library. Feel free to ask more questions.)

**Comment by flatsiedatsie** [comment]
`npm run run-only`

Halleluja!

Meanwhile, I'm having some trouble getting my add-on to react to an API request.

In the console I can see that when the UI calls `http://localhost:8080/extensions/Candle-manager-addon/api/example-api?samplekey=samplevalue`, it received a `404` error. 

Right at the top of `def handle_request(self, request):` I have set it up to [print a message](https://github.com/createcandle/Candle-manager-addon/blob/master/pkg/api_handler.py), to indicate that it was called. But it never shows up.

As with the "notifier inside the adapter" situation, I [attached the API handler](https://github.com/createcandle/Candle-manager-addon/blob/master/pkg/candle_adapter.py#L226) to the main adapter init:
`self.extension = CandleManagerAPIHandler(self,verbose=True)` ( I added the extra 'self' )

In the logs I can see that the API handler is being initiated: `AddonManagerProxy: add_api_handler: Candle-manager-addon` (actually, it shows that twice in a row, strange)

Yet somehow the `handle_request` is never called.

The example add-on _does_ work.

I'm sure I'll figure it out eventually, but in case you spot the error in 2 seconds, I'd love to know :-)

// update: I just noticed this in the Firefox console:
```
 Firefox can’t establish a connection to the server at ws://localhost:8080/things?jwt=eyJhbGciOiJFUzI1NiIsInR-etc
```
// I think that's unrelated.

Could the issue be that the adapter and extension have the same name? `Candle-manager-addon`?

I tried to rename all the parts related to the API handler `Candle-manager-addon-ext`, but what didn't work.

**Comment by flatsiedatsie** [comment]
More generally, I wonder how graceful degradation/upgrading could be achieved. An in general I guess it's not very clear to me how I could make an adapter-extension hybrid.

**Comment by mrstegeman** [comment]
You didn’t register your handler with the gateway. See: https://github.com/mrstegeman/example-extension/blob/python/pkg/example_api_handler.py#L23

**Comment by flatsiedatsie** [comment]
- I noticed that the settings input fields for the add-on are in a different (random?) order.

**Comment by flatsiedatsie** [comment]
I would never had found that :-D

**Comment by mrstegeman** [comment]
The fields are probably in a different order in your manifest.json than they are in your package.json.

**Comment by flatsiedatsie** [comment]
Ah thanks, I'll check.

Registering with the gateway, how do I do that? I tried this:
`self.adapter.manager_proxy.add_api_handler(self)` to get it 'up a level', to the adapter.

I checked, and it's indeed an existing object.
```
ext: self.adapter.manager_proxy = <gateway_addon.addon_manager_proxy.AddonManagerProxy object at 0x10df99750>`
```

I also tried doing it at the adapter level:
```
            self.extension = CandleManagerAPIHandler(self, verbose=True)
            self.manager_proxy.add_api_handler(self.extension)
```

Could the issue be that in the manifest it says `"primary_type": "extension",`, even though it's actually still a normal adapter?

// Update: set the 'primary type' to 'adapter'. Everything still works... and the API handler still doesn't.

**Comment by flatsiedatsie** [comment]
Some more thoughts I will be testing shortly:
- Is an extensions' JS unloaded when its view is navigated away from? (I assume so)
- Is jQuery available? I suspect not.. Are extensions allowed to load jQuery? 

For the time being (and because I can't get it to work :-D ), I suspect the Candle Manager add-on will still have to connect to a Flask server as its API. It's the only way to make it easily compatible with < 0.10 installations.

I'd love to fully switch to 0.10 and use the API handler. But I suspect the new version of the gateway won't be ready before the Candle launch. So close!

**Comment by flatsiedatsie** [comment]
Wow, it seems the add-on JS is loaded immediately as the gateway loads. I didn't expect that. That's going to make for a very heavy page if all kinds of extensions are active at the same time?

On the other hand, this would mean that extensions could totally overhaul the UI.
In theory an add-on could read data from all the things as they are displayed on screen, and siphon the data away?

**Comment by flatsiedatsie** [comment]
Whoa, CSS too. I guess the Gateway now has theme support :-D

**Comment by flatsiedatsie** [comment]
- Loading data from the existing Flask API is not possible, as it would be cross site scripting. 

Surprisingly, an iframe to an external site gives a similar error:
```
Firefox prevented this page from loading in this way because the page has a content security policy that disallows it.
```

Does the Gateway have some kind of elevated security level?

Luckily, loading `localhost:8686` worked ok.


- What is the preferred way of doing CSS? Should each element have it's own prefixed ID or class name? Or could CSS just do a lot of:
```
#uniqueAddOnContainer .elementname > a
#uniqueAddOnContainer textarea
#uniqueAddOnContainer div > input
```

**Comment by flatsiedatsie** [comment]
- If you make the content area of the extension full width and height, the `menu-button` disappears beneath it. It might be wise to have that button be on top by default? Then, if an add-on then really wanted to, it could still go over its z-index, but at least it wouldn't happen by default?
- Similarly, it would be great if the 2rem padding on the `html` element could be removed. That way add-ons could go full-width or full-height without needing to modify the general Gateway CSS.

E.g. photo frame add-on, needing an iframe, full-width dataviz, completely different data dashboard, etc.

**Comment by flatsiedatsie** [comment]
Strange error while trying to run the localhost today:

```
Error: Cannot find module '/Users/username/gateway/node_modules/sqlite3/lib/binding/node-v72-darwin-x64/node_sqlite3.node'
Require stack:
- /Users/username/gateway/node_modules/sqlite3/lib/sqlite3.js
- /Users/username/gateway/build/gateway.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
    at Function.Module._load (internal/modules/cjs/loader.js:618:27)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/username/gateway/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)

```

**Comment by flatsiedatsie** [comment]
I could upload the new version of the add-on. Or is there still a chance that the add-on system will change significantly before the release?

**Comment by mrstegeman** [comment]
> Registering with the gateway, how do I do that? I tried this:
> `self.adapter.manager_proxy.add_api_handler(self)` to get it 'up a level', to the adapter.
> 
> I checked, and it's indeed an existing object.
> 
> ```
> ext: self.adapter.manager_proxy = <gateway_addon.addon_manager_proxy.AddonManagerProxy object at 0x10df99750>`
> ```
> 
> I also tried doing it at the adapter level:
> 
> ```
>             self.extension = CandleManagerAPIHandler(self, verbose=True)
>             self.manager_proxy.add_api_handler(self.extension)
> ```

It'd be easiest for me to just take a look.

> Could the issue be that in the manifest it says `"primary_type": "extension",`, even though it's actually still a normal adapter?

No, that wouldn't matter.

**Comment by mrstegeman** [comment]
> * Is an extensions' JS unloaded when its view is navigated away from? (I assume so)

No.

> * Is jQuery available? I suspect not.. Are extensions allowed to load jQuery?

Sure, if you load it. Please do not load it globally into the window, though, i.e. keep it local to your extension.

> For the time being (and because I can't get it to work :-D ), I suspect the Candle Manager add-on will still have to connect to a Flask server as its API. It's the only way to make it easily compatible with < 0.10 installations.
> 
> I'd love to fully switch to 0.10 and use the API handler. But I suspect the new version of the gateway won't be ready before the Candle launch. So close!

The flask workaround is only going to work locally, when you're connecting to localhost. The API handler was created as a way to do things properly. But no, for < 0.10, there is not a better solution.

**Comment by mrstegeman** [comment]
> Wow, it seems the add-on JS is loaded immediately as the gateway loads. I didn't expect that. That's going to make for a very heavy page if all kinds of extensions are active at the same time?

Potentially, but after the initial load, everything should be snappy. This seemed like a better way to go than loading/unloading all the time.

> On the other hand, this would mean that extensions could totally overhaul the UI.

Yes.

> In theory an add-on could read data from all the things as they are displayed on screen, and siphon the data away?

Yes. An add-on could already do that, though.

**Comment by mrstegeman** [comment]
> Whoa, CSS too. I guess the Gateway now has theme support :-D

That was the idea. :smiley:

**Comment by mrstegeman** [comment]
>> * Loading data from the existing Flask API is not possible, as it would be cross site scripting.
> 
> Surprisingly, an iframe to an external site gives a similar error:
> 
> ```
> Firefox prevented this page from loading in this way because the page has a content security policy that disallows it.
> ```
> 
> Does the Gateway have some kind of elevated security level?

No, this is just standard web browser stuff. One of the many reasons I didn't want to use iframes.

> * What is the preferred way of doing CSS? Should each element have it's own prefixed ID or class name? Or could CSS just do a lot of:
> 
> 
> ```
> #uniqueAddOnContainer .elementname > a
> #uniqueAddOnContainer textarea
> #uniqueAddOnContainer div > input
> ```

You can do what you want, but I would prefer it if you would namespace all of your IDs and classes, e.g. "extension-candle-manager-addon-class1". It's quite verbose, but we don't have to worry about conflicting names that way. This is what I did in the example-extension.

**Comment by mrstegeman** [comment]
> * If you make the content area of the extension full width and height, the `menu-button` disappears beneath it. It might be wise to have that button be on top by default? Then, if an add-on then really wanted to, it could still go over its z-index, but at least it wouldn't happen by default?

I intentionally didn't apply global CSS to all extensions, for exactly this reason. The add-on could just override it anyway. Didn't seem like it was worth my time. The example-extension has some basic CSS which draws the frame to the proper size.

> * Similarly, it would be great if the 2rem padding on the `html` element could be removed. That way add-ons could go full-width or full-height without needing to modify the general Gateway CSS.

Ditto above. Also, that 2rem padding is there for a reason.

**Comment by mrstegeman** [comment]
> Strange error while trying to run the localhost today:
> 
> ```
> Error: Cannot find module '/Users/username/gateway/node_modules/sqlite3/lib/binding/node-v72-darwin-x64/node_sqlite3.node'
> Require stack:
> - /Users/username/gateway/node_modules/sqlite3/lib/sqlite3.js
> - /Users/username/gateway/build/gateway.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:618:27)
>     at Module.require (internal/modules/cjs/loader.js:771:19)
>     at require (internal/modules/cjs/helpers.js:68:18)
>     at Object.<anonymous> (/Users/username/gateway/node_modules/sqlite3/lib/sqlite3.js:4:15)
>     at Module._compile (internal/modules/cjs/loader.js:868:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
>     at Module.load (internal/modules/cjs/loader.js:731:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:644:12)
>     at Module.require (internal/modules/cjs/loader.js:771:19)
> ```


You probably need to run `npm install` in the gateway.

**Comment by mrstegeman** [comment]
> I could upload the new version of the add-on. Or is there still a chance that the add-on system will change significantly before the release?

Please push to GitHub if you want me to take a look at your API handler issues. The major add-on system changes should be done now.

**Comment by flatsiedatsie** [comment]
I've [uploaded the code](https://github.com/createcandle/Candle-manager-addon). No rush though, I won't have time to really move everything to the new API handler system for a while. 

> The flask workaround is only going to work locally, when you're connecting to localhost. 

Darn. Still, for now having the iframe inside the UI will allow me to showcase the project well on the exhibition floor and in videos.

The more I think about it, the more impressed by your creation I get. You could build entire Gateway features in this, as long as they don't need to hook into the rest of the system too much (or if the rest of the system if 'hookable' with API's somehow)

I'll trust you on the JS not becoming too heavy for the page :-)

> n theory an add-on could read data from all the things as they are displayed on screen, and siphon the data away? -> Yes. An add-on could already do that, though.

True. It just feels like there's more and more code for you guys to police. The code obfuscation potential may grow.

> I would prefer it if you would namespace all of your IDs and classes, e.g. "extension-candle-manager-addon-class1"

I agree that's best, and have already [prepared the view](https://github.com/createcandle/Candle-manager-addon/blob/master/views/content.html) in anticipation of having time to work on this more.

> I intentionally didn't apply global CSS to all extensions, for exactly this reason. 

Nice.

> The add-on could just override it anyway. Didn't seem like it was worth my time. The example-extension has some basic CSS which draws the frame to the proper size.

My thought are that, just as add-ons shouldn't make changes to the OS that could affect other add-ons, it would be great if these extensions didn't have to mess with 'global' CSS to achieve goals.

For example, my add-on could shift the hamburger menu icon to a higher z-index, but then other extensions might be affected. If its Z-index was just slightly higher by default (say, 2), then extensions could put themselves above or below the hamburger without affecting other extensions.

The same thing goes for the html padding. I understand it's useful, but it does hinder some use cases. Extensions could force the html to not have a padding, but that would affect everything if that styling wasn't removed when extension 'closes'. 

I guess add-ons could absolutely position themselves to reach the full width and height, but ideally that wouldn't be necessary?

I'm really looking forward to making a photo frame add-on.


- Another question: would extensions be allowed to change the menu icon on the fly? For example, if they require attention by the user a little (!) could be shown on it.  

- I'm also thinking it could be interesting to make an add-on that does only one basic thing: toggle full screen display. This would be great for tablets. When the webpage is in normal mode, it could show a "go fullscreen" icon. When it's fullscreen, it could show an "exit fullscreen" icon. Perhaps even the menu item text could be changed. How does this idea sound?

**Comment by mrstegeman** [comment]
> * Another question: would extensions be allowed to change the menu icon on the fly? For example, if they require attention by the user a little (!) could be shown on it.

I don't see why not.

> * I'm also thinking it could be interesting to make an add-on that does only one basic thing: toggle full screen display. This would be great for tablets. When the webpage is in normal mode, it could show a "go fullscreen" icon. When it's fullscreen, it could show an "exit fullscreen" icon. Perhaps even the menu item text could be changed. How does this idea sound?

Go for it! Could be useful in some cases.

**Comment by flatsiedatsie** [comment]
Great!

**Comment by flatsiedatsie** [comment]
The Candle Manager add-on works in that it creates a tab with the interface (inside an iframe for now). However, if I navigate away from the page (e.g. visiting the 'things' page) and then return to it, the content is gone. An empty page is shown.

After a page refresh the Candle Manager can be opened again (once).

**Comment by mrstegeman** [comment]
My best guess is that there's an issue with the `show()` method of your extension. The example-extension doesn't exhibit this behavior.
