### ISSUE TITLE
Battery level

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway-addon-python#76]
Is there an 'official' way to have things represent their current battery level? I looked in the schema but couldn't find anything.

(Some MySensors users [asked about it](https://forum.mysensors.org/topic/10342/mozilla-webthings-mysensors-add-on-adapter/41)).

**Comment by mrstegeman** [comment]
See: mozilla-iot/schemas#33

Otherwise, I'd just use a `LevelProperty`.
