### ISSUE TITLE
How to reboot

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway-addon-python#80]
The Power Settings add-ons has a reboot functionality. I changed it to use the internal api, per your request. But it doesn't seem to work anymore?

`window.API.postJson('/system/actions', {action: 'restartSystem'}).catch(console.error);`

**Comment by mrstegeman** [comment]
Your URL is wrong. It should be `/settings/system/actions`.

(Sorry, just realized I told you wrong before.)

**Comment by flatsiedatsie** [comment]
No problem! The odd thing is it seemed to work before :-D
