### ISSUE TITLE
How to deal with properties that don't have a value yet

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway-addon-python#81]
How would you advise the following situation be handled?

- A sensor doesn't send its first measurement until a minute after it boots up.
- I would like to present the property to the gateway in the meantime, even though there is no value for it yet. Otherwise a user may get confused about seeing an empty device.

I could set the property to zero, but that creates other issues. It could trigger rules, or just be confusing. ("The temperature sensor says it's 0 degrees outside, even though it's a warm summer day").

So ideally I'd like to have it show something that indicates the property exists, but no data has been received for it yet. Is this possible?

Can I send a `null` value?

**Comment by mrstegeman** [comment]
You _could_ send `null`, or you could persist the last received value to a file which you would then read back when your adapter starts up.

**Comment by flatsiedatsie** [comment]
Thanks!
