### ISSUE TITLE
Restart the addon?

### ISSUE THREAD

**Issue by createcandle** [WebThingsIO/gateway-addon-python#85]
Is there a recommended way that an addon can restart itself? I tried using `sys.exit()` in the hopes that the gateway would then restart it as if it had crashed. But it did nothing.

**Comment by mrstegeman** [comment]
If the add-on process exits with any code besides `100`, the gateway should automatically restart. You need to make sure you're killing off every thread and process owned by the add-on, though. You should see a message in the gateway log, similar to: `Plugin: <id> died, code = <code> restarting after <X>`
