### ISSUE TITLE
Uninstall method

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway-addon-python#90]
Addon already have a very useful `unload` method that is called when they are disabled. I wonder, would it be an idea to have an 'uninstall' method that is called when an addon is uninstalled? Then it could quickly remove some files from `.webthings/data`.

**Comment by mrstegeman** [comment]
Duplicate of https://github.com/WebThingsIO/gateway/issues/2062

**Comment by flatsiedatsie** [comment]
Apologies. I'm starting to forget the things I asked for earilier.. I'll do a better search next time.
